REVOKE ALL PRIVILEGES, GRANT OPTION FROM '${EC_APP_USERNAME}'@'%';

GRANT SELECT, INSERT, UPDATE, DELETE
      ON ${DB_NAME}.*
          TO '${EC_APP_USERNAME}'@'%';

GRANT CREATE, ALTER, DROP, INDEX
ON ${DB_NAME}.*
TO '${EC_MIGRATE_USERNAME}'@'%';

FLUSH PRIVILEGES;